version: "2"
linters:
  default: none
  enable:
    - depguard
    - staticcheck
    - unconvert
    - unused
  settings:
    depguard:
      rules:
        forbid-pkg-errors:
          deny:
            - pkg: github.com/pkg/errors
              desc: Should be replaced with standard lib errors or fmt.Errorf
            - pkg: io/ioutil
              desc: Use corresponding 'os' or 'io' functions instead.
            - pkg: github.com/pkg/errors
              desc: Use 'errors' or 'fmt' instead of github.com/pkg/errors
    errcheck:
      exclude-functions:
        - scripts/errcheck_excludes.txt
    testifylint:
      enable:
        - bool-compare
        - compares
        - empty
        - error-is-as
        - error-nil
        - float-compare
        - len
        - suite-dont-use-pkg
        - suite-extra-assert-call
        - suite-thelper
      disable:
        - require-error
        - expected-actual
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  settings:
    gci:
      sections:
        - standard
        - default
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
