name: Bug Report
description: Create a report to help us improve
title: "[name of bug] Issue Title"
labels: [bug]
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please be cautious with the sensitive information/logs while filing the issue.
  - type: textarea
    id: desc
    attributes:
      label: Describe the bug a clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Enter exactly what happened.
    validations:
      required: false

  - type: textarea
    id: what-expected
    attributes:
      label: What you expected to happen?
      description: Enter what you expected to happen.
    validations:
      required: false

  - type: textarea
    id: how-to-reproduce
    attributes:
      label: How to reproduce it?
      description: As minimally and precisely as possible.
    validations:
      required: false

  - type: textarea
    id: changed-values
    attributes:
      label: Enter the changed values of values.yaml?
      description: Please enter only values which differ from the defaults. Enter `NONE` if nothing's changed.
      placeholder: 'key: value'
    validations:
      required: false

  - type: textarea
    id: helm-command
    attributes:
      label: Enter the command that you execute and failing/misfunctioning.
      description: Enter the command as-is as how you executed.
      placeholder: 'key: value'
    validations:
      required: true

  - type: textarea
    id: anything-else
    attributes:
      label: Anything else we need to know?
    validations:
      required: false
